version: '3.5'

networks:
  mainnetwork:
    name: mainnetwork
    driver: bridge

services:
  caddy:
    restart: always
    container_name: con_caddy
    build:
      dockerfile: Dockerfile
      context: ./caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/caddy_data:/data
    networks:
      - mainnetwork
        
  carbonclicks_app:
    restart: always
    container_name: con_carbonclicks_app
    deploy: 
      mode: replicated
      replicas: 2
    build:
      dockerfile: Dockerfile
      context: ./
    networks: 
      - mainnetwork

  carbonclicks_database:
    # Do not change this image without having a full migration plan ready 
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: can_carbonclicks_database
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    environment:
      env_file: 
        - .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_WALDIR: /wal
    networks:
      - mainnetwork
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data/pgdata
      - ${PGWAL}:/wal
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

volumes:
  carbonclicks_database:
    external: true
  caddy:
    external: true
  



